// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://preguvwoowqaeoswwwdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZWd1dndvb3dxYWVvc3d3d2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzQ4MTMsImV4cCI6MjA2NjQ1MDgxM30.5Y1vwkSnBiV9c50NrSKgk3XsqolDajFHCrH9lNJnvqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);